### PR TITLE
Demonstration of OO-extensibility failure of #generate_solr_document

### PR DESCRIPTION
**Pull request by atz**
when used with passed block.

Note the same test expectation (that the yielded object is the same as the object returned), passes with the base case, but fails once the class is extended and the method overridden.  This is not a pathological example, since it is exactly how we have been telling consumers to
extend this class (among others). The problem has to do with the "timing" of the yield, happening at the end of the base class method, not at the end of the overriding method.  There is no apparent fix for this problem.

### CODE REVIEW

**Comment by atz** [comment]
I guess we don't have CI as a prerequisite for merge here...

**Comment by jcoyne** [comment]
Was this supposed to fail?

**Comment by atz** [comment]
There's apparently no CI check here, like I said.  Possibly has to do w/ renaming of the repo.

**Comment by atz** [comment]
build DID fail here: https://travis-ci.org/projecthydra/hydra-pcdm/builds/236172526

**Comment by jcoyne** [comment]
@atz I see, this repo dosen't show build status, so I just see the green button.

**Comment by atz** [comment]
New build running: https://travis-ci.org/projecthydra/hydra-pcdm/builds/236176095

**Comment by atz** [comment]
@jcoyne OK, that got the expected failure.

**Comment by atz** [comment]
Reverted the underlying feature

**Pull request closed without merging**
